//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> AssessmentStatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string Reference { get; set; }
        public string OtherReference { get; set; }
        public string CustomerReference { get; set; }
        public string PolicyReference { get; set; }
        public string SurveyJSON { get; set; }
        public string SurveyJSONResult { get; set; }
        public Nullable<decimal> Quote { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressInstructions { get; set; }
        public string ContactPerson { get; set; }
        public string ContactCellphone { get; set; }
        public string ContactEmail { get; set; }
        public string ReceipientName { get; set; }
        public string ReceipientSignature { get; set; }
        public Nullable<int> ReceipientOTP { get; set; }
        public string ReceipientFeedback { get; set; }
        public Nullable<int> ReceipientRating { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
        public string InsurerName { get; set; }
        public string InsurerContactPerson { get; set; }
        public string InsurerContactNumber { get; set; }
        public string InsurerPolicyNumber { get; set; }
        public string BrokerName { get; set; }
        public string BrokerContactNumber { get; set; }
        public string InsuredName { get; set; }
        public string InsuredContactNumber { get; set; }
        public string InsuredIndustrySector { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public string InsurerEmailAddress { get; set; }
        public string InsuredEmailAddress { get; set; }
        public string BrokerEmailAddress { get; set; }
        public Nullable<int> NewPolicy { get; set; }
        public Nullable<int> FileUploadCapture { get; set; }
        public Nullable<int> IndustrySectorID { get; set; }
        public Nullable<int> IndustrySubSectorID { get; set; }
        public Nullable<int> IndustrySectorClassID { get; set; }
        public Nullable<decimal> EML { get; set; }
        public Nullable<decimal> MPL { get; set; }
        public string RiskComments { get; set; }
        public string MPLComments { get; set; }
        public string EMLComments { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingConfirmedBy { get; set; }
        public string BookingConfirmedByContact { get; set; }
        public string BookingNote { get; set; }
        public string Special { get; set; }
        public Nullable<int> isInternal { get; set; }
        public string ClaimNumber { get; set; }
        public string InsurerFunction { get; set; }
        public string BrokerFunction { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string BuildingName { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string Suburb { get; set; }
        public string PostalCode { get; set; }
        public Nullable<decimal> TotalValuationAmmount { get; set; }
        public string BrokerContactPerson { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    }
}
