//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAsset
    {
        public int ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetClassID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SKU { get; set; }
        public Nullable<int> UOM_ID { get; set; }
        public string Measurement { get; set; }
        public Nullable<int> ProofOfPurchaseTypeID { get; set; }
        public string ProofOfPurchaseReference { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Specified { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string Supplier { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    }
}
