//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentRiskClassificationSummary
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentRiskFactorID { get; set; }
        public Nullable<int> AssessmentPolicyElementsID { get; set; }
        public Nullable<int> AssessmentRiskRatingID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
    }
}
