//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPolicyDetail
    {
        public int ID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> ElementID { get; set; }
        public Nullable<int> Covered { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
    }
}
