//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentClientBooking
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string OTP { get; set; }
        public Nullable<int> OTPConfirmed { get; set; }
        public Nullable<System.DateTime> OTPDateSent { get; set; }
        public Nullable<System.DateTime> OTPConfirmedDate { get; set; }
        public string Note { get; set; }
    }
}
