//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentDocument
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Type { get; set; }
        public System.DateTime uDate { get; set; }
        public string FileName { get; set; }
    }
}
