//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuote
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Quote { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> ValidUntillDate { get; set; }
        public Nullable<int> QuoteStatusID { get; set; }
        public Nullable<int> QuoteUserID { get; set; }
        public Nullable<System.DateTime> QuoteStatusDate { get; set; }
        public Nullable<int> QuoteCardID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> SurchargeFee { get; set; }
        public Nullable<decimal> AssessorTotal { get; set; }
        public Nullable<decimal> SpecialistTotal { get; set; }
        public Nullable<decimal> ProfitTotal { get; set; }
        public Nullable<decimal> InitialQuoted { get; set; }
        public Nullable<int> AssessmentRateCardID { get; set; }
        public string VAT_Code { get; set; }
        public decimal VAT_AMOUNT { get; set; }
        public string CALC { get; set; }
    }
}
