//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMediaItem
    {
        public int ID { get; set; }
        public Nullable<int> AssetMedia { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string DurationAt { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
