//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAddress
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string Unit { get; set; }
        public string BuildingName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactName { get; set; }
        public int AddressStatusID { get; set; }
    }
}
