//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentRateCard
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> ValuationFrom { get; set; }
        public Nullable<decimal> ValuationTo { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> InsurerRateCardID { get; set; }
    }
}
