//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSurveyAssociation
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<System.DateTime> aDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
