//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPS_Statement
    {
        public int ID { get; set; }
        public string CISNumber { get; set; }
        public string ProfileNumber { get; set; }
        public string Product { get; set; }
        public string InstanceNumber { get; set; }
        public string InstanceName { get; set; }
        public string Date { get; set; }
        public string TransactionKey { get; set; }
        public string ProcessKey { get; set; }
        public string ResendKey { get; set; }
        public string DestinationKey { get; set; }
        public string TransactionListNumber { get; set; }
        public string StatementLineNumber { get; set; }
        public string Account { get; set; }
        public string TransactionCode { get; set; }
        public string SubTransactionCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DebitCredit { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<decimal> AccountAvailableBalance { get; set; }
        public string UserRef { get; set; }
    }
}
