//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoStamp
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Speed { get; set; }
        public string Altitude { get; set; }
    }
}
