//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentsAllStats_Result1
    {
        public int Created { get; set; }
        public int Quoting { get; set; }
        public int In_Progress { get; set; }
        public int Complete { get; set; }
        public int Failed { get; set; }
        public int Cancelled { get; set; }
        public Nullable<int> QA { get; set; }
    }
}
