//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentRequirementDocuments_Result1
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentRequirementID { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
    }
}
