//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentGeneralInformation_Result4
    {
        public int AssessmentID { get; set; }
        public Nullable<int> AssessmentStatusID { get; set; }
        public string AssessmentStatusDescription { get; set; }
        public string InsurerName { get; set; }
        public string InsurerContactPerson { get; set; }
        public string InsurerContactNumber { get; set; }
        public string InsurerPolicyNumber { get; set; }
        public string BrokerName { get; set; }
        public string BrokerContactNumber { get; set; }
        public string InsuredName { get; set; }
        public string InsuredContactNumber { get; set; }
        public string InsuredIndustrySector { get; set; }
        public string InsuredEmailAddress { get; set; }
        public string InsurerEmailAddress { get; set; }
        public string BrokerEmailAddress { get; set; }
        public Nullable<int> NewPolicy { get; set; }
    }
}
