//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentValuationsAllActive_Result3
    {
        public int QuoteID { get; set; }
        public int Valuation { get; set; }
        public string Type { get; set; }
        public string Date { get; set; }
        public string Reference { get; set; }
        public string Client { get; set; }
        public string Insurer { get; set; }
        public string Broker { get; set; }
        public string Address { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
    }
}
