//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentMovableAssetsValuationPropertyDetails_Result2
    {
        public int ID { get; set; }
        public Nullable<int> TypeOfResidenceID { get; set; }
        public Nullable<int> RoofConstructionID { get; set; }
        public Nullable<int> VicinityID { get; set; }
        public Nullable<int> ExtendoflandID { get; set; }
        public Nullable<int> BordersID { get; set; }
        public string AddressGeneralComments { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> PostalCodeID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> BuildingTypeID { get; set; }
        public Nullable<int> AccessControl { get; set; }
        public Nullable<int> ArmedResponse { get; set; }
        public Nullable<int> CCTV { get; set; }
        public Nullable<int> PerimeterWall { get; set; }
        public Nullable<int> ElectricFence { get; set; }
        public Nullable<int> BarbedWire { get; set; }
        public Nullable<int> Guards { get; set; }
        public Nullable<int> SecurityGate { get; set; }
        public Nullable<int> InternalSecurityBeams { get; set; }
        public Nullable<int> ExternalSecurityBeams { get; set; }
        public Nullable<int> AlarmSystem { get; set; }
        public Nullable<int> WindowSecurity { get; set; }
        public string SecurityGeneralComments { get; set; }
        public Nullable<int> FireThatch { get; set; }
        public Nullable<int> FireWoodenStruct { get; set; }
        public Nullable<int> FireFighthingEquipment { get; set; }
        public string OtherFireRisk { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string Suburb { get; set; }
        public string PostalCode { get; set; }
        public string FireGeneralComments { get; set; }
    }
}
