//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentRequirements_Result1
    {
        public int ID { get; set; }
        public string AreaOfObservation { get; set; }
        public string RiskRating { get; set; }
        public string Deadline { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Details { get; set; }
    }
}
