//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getAssessmentAssignedUsers_Result1
    {
        public Nullable<int> UserTypeID { get; set; }
        public string UserTypeDescription { get; set; }
        public string UserPicture { get; set; }
        public string UserFirstName { get; set; }
        public string UsersLastName { get; set; }
        public string Adderess { get; set; }
        public string UserCellphone { get; set; }
        public string FireBaseMessengerID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string AssessmentUserAsignedDate { get; set; }
    }
}
