//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    
    public partial class getRiskManagementTotals_Result1
    {
        public Nullable<int> High_Risk { get; set; }
        public Nullable<int> Medium_Risk { get; set; }
        public Nullable<int> Low_Risk { get; set; }
        public Nullable<int> Pending_Requirements { get; set; }
        public Nullable<int> Completed_Requirements { get; set; }
        public string Risk_Management_KPI { get; set; }
    }
}
