//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class lh_OccupationPermission
    {
        public int ID { get; set; }
        public int OccupationID { get; set; }
        public int ModuleID { get; set; }
        public int FeatureID { get; set; }
        public int StateID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
    }
}
