//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Tell { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
        public string RegNo { get; set; }
        public string VatNo { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
    }
}
