//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public Nullable<int> SocketID { get; set; }
        public Nullable<int> Active { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Pin { get; set; }
        public string Token { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    }
}
