//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public Nullable<int> FromAccountID { get; set; }
        public Nullable<int> ToAccountID { get; set; }
        public string FromReference { get; set; }
        public string ToReference { get; set; }
        public Nullable<int> TransactionStatusID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> CreditNoteID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
