//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Pin { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string Picture { get; set; }
        public string Wallpaper { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> IdentityTypeID { get; set; }
        public string FirebaseID { get; set; }
        public string FirebaseMessengerID { get; set; }
        public string signature { get; set; }
    }
}
