//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitig8
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletAccount
    {
        public int ID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> WalletID { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<decimal> Pending { get; set; }
    }
}
